# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#

puts "🍜 Seeding data..."


menu = Menu.create([
    {name: "Salads", image_url: "https://nbtrangmanchclub.com/wp-content/uploads/2017/10/Soups-4.png"},
    {name: "Meats", image_url: "https://vgmeats.ca/content/uploads/the-ethics-of-food-and-why-we-care.jpg"},
    {name: "Soup", image_url: "https://www.thespruceeats.com/thmb/KviPmdjGAR_7dQy1t2UtoicVb9c=/3550x2366/filters:fill(auto,1)/african-peanut-butter-soup-recipe-39554-hero-01-5d04efd6e03a43b68710a1d44b55607b.jpg"},
    {name: "Vegan", image_url: "https://www.femalefirst.co.uk/image-library/land/1000/v/vegan-food-jaywing-pr.jpg"}

])

menu_item = MenuItem.create([
    {name: "Irio", image_url: "http://africanmiliki.com/images/Irio.jpg", description: "Mashed potatoes and peas mixed with corn and onions seasoned with black pepper and salt", price: 300, menu_id: 1},
    {name: "Coconut Rice", image_url: "http://africanmiliki.com/images/coconut-rice-dish.jpg", description: "Long grain rice cooked in chicken broth and freshly squeezed coconut milk seasoned with oma's Jollof Rice Seasoning and a dash of nutmeg", price: 300, menu_id: 1},
    {name: "Chicken Pepper Soup", image_url: "http://africanmiliki.com/images/chicken-pepper-soup.jpg", description: "Stewing chicken cooked, deboned, diced and allowed to simmer in chicken stock and oma's Pepper Soup Seasoning until perfect '. . . for the soul'", price: 300, menu_id: 1},
    {name: "Goat Meat Pepper", image_url: "http://africanmiliki.com/images/Goat-pepper-soup-bowl.jpg", description: "A medly of diced goat tripe and organ meat simmered in it's own broth and oma's Pepper Soup Seasoning get's the stomach ready for more goodness. *Hot pepper powder as well as bitter utazi powder is available on demand", price: 300, menu_id: 1},
    {name: "Nsala", image_url: "http://africanmiliki.com/images/Nsala-soup.jpg", description: "Oxtail slow cooked until soft in onion water seasoned with oma's Jollof Rice Seasoning, then deboned and diced except for the tiny ends. A further simmering in its own stock thickened with tomato paste to which more of the seasoning has been added takes this simple soup to beyond yummy!", price: 300, menu_id: 1},
    {name: "Oxtail", image_url: "http://africanmiliki.com/images/oxtail-soup-bowl.jpg", description: "Cut up fresh catfish fillet is added to a simmering pot of liquefied onion, tomato and dry crayfish aromatized with oma's Pepper Soup Seasoning then thickened with yam powder. *Hot pepper powder as well as bitter utazi powder is available on demand", price: 300, menu_id: 1},


    {name: "Nyama Choma", image_url: "https://cdn.tasteatlas.com/images/dishes/632c5f0e3bc94f1784c1c6c89bf03d2e.jpg?mw=1300", description: "Nyama choma is Kenya's unofficial national dish, meaning barbecued meat in the Swahili language. The meat is usually goat or beef, served roasted throughout the country, from roadside shacks to fine restaurants. It is often paired with local beer and side dishes such as ugali.", price: 650, menu_id: 2},
    {name: "Peri Peri Chicken", image_url: "https://cdn.tasteatlas.com/images/dishes/c6b34701a6774dca83b486992d618a4c.jpg?mw=1300", description: "Peri peri chicken is a Mozambican dish consisting of grilled or roasted chicken that is often served with a creamy and spicy coconut sauce. Before grilling, the meat is traditionally marinated in cumin, garlic, paprika, lemon juice, and bird's eye chilis, giving the chicken a unique flavor.", price: 650, menu_id: 2},
    {name: "Bunny Chow", image_url: "https://cdn.tasteatlas.com/Images/Dishes/26ac876911e042cd87c6e6be20135d73.jpg?mw=1300", description: "Bunny chow is a South African dish consisting of a half or a quarter loaf of bread that is hollowed out and stuffed with curry that has been cooked with kidney beans or meats such as mutton, chicken, and lamb. It is traditionally consumed without utensils.", price: 650, menu_id: 2},
    {name: "Sambusa", image_url: "https://cdn.tasteatlas.com/images/dishes/8fe2189a9a6e4815907eeef210c855c5.jpg?mw=1300", description: "Tibs is an Ethiopian dish consisting of stir-fried meat and vegetables. The dish can be served in a wide variety of manners – ranging from mild to hot and containing a small amount of vegetables, lots of vegetables, or no vegetables at all.", price: 650, menu_id: 2},
    {name: "Yassa", image_url: "https://cdn.tasteatlas.com/Images/Dishes/c5c5d59e95d9475ba7426a57830e10ea.jpg?mw=1300", description: "Yassa is Senegal's national dish, a stew consisting of chicken that is marinated in lemon, lots of onions, and vinegar. The chicken needs to marinate in the mixture for at least eight hours, making sure that the lemon juice and vinegar take the bite out of the onions and tenderize the tough poultry found in the Casamance region.", price: 650, menu_id: 2},
    {name: "Kitfo", image_url: "https://cdn.tasteatlas.com/Images/Dishes/1da821e8c98a42f38ede3fd8556652d2.jpg?mw=1300", description: "Kitfo is a popular Ethiopian dish consisting of raw beef that is freshly ground and combined with Ethiopian butter (niter kibbeh) and spices such as chili and salt. The dish is served with a variety of breads, with injera being a staple of every restaurant that serves kitfo.", price: 650, menu_id: 2},


    {name: "Harira", image_url: "https://cdn.tasteatlas.com/Images/Dishes/31c8c0d449884b7692a0b12910f25687.jpg?mw=1300", description: "Harira is made from a variety of legumes such as lentils, fava beans, and chickpeas, tomato sauce, harissa paste, and fresh herbs such as parsley, turmeric, saffron, lemon, caraway seeds, and coriander, but every region in Morocco has its own version of the soup.", price: 400, menu_id: 3},
    {name: "Lablabi", image_url: "https://cdn.tasteatlas.com/Images/Dishes/74219c2b001f4fbd80ef418ae398d142.jpg?mw=1300", description: "It is traditionally served ladled over chunks of stale crusty bread, drizzled with olive oil, sometimes even with either vinegar or lemon or lime juice, and often garnished with cilantro, parsley, and scallions. Special versions of lablabi include capers, olives, pickled vegetables and tuna, while another variety called hergma is made with cow's hooves.", price: 400, menu_id: 3},
    {name: "Besara", image_url: "https://cdn.tasteatlas.com/images/dishes/2680250fc980401aa4c17098057baed6.jpg?mw=1300", description: "Bessara is a comforting Moroccan dish made with puréed beans – either split peas or dried fava beans. It can be prepared in the form of a soup or porridge, while the thicker versions are commonly used as a dip. The puréed beans are typically seasoned with olive oil, lemon juice, and garlic, and the dish is often served with paprika and cumin on the side, while crusty Moroccan bread is almost mandatory.", price: 400, menu_id: 3},
    {name: "Banga Soup", image_url: "https://cdn.tasteatlas.com/images/dishes/2ca9862fc6ad46d299a714c04109903c.jpg?mw=1300", description: "Banga or ofe akwu is a flavorful Nigerian soup made with palm fruit, beef or dried fish, vegetables, and seasonings such as salt and chili pepper. The soup is traditionally paired with various fufu dishes. The name of the dish is derived from two words: ofe, meaning soup or stew, and akwu, meaning palm fruit.", price: 400, menu_id: 3},
    {name: "Achu Soup", image_url: "https://cdn.tasteatlas.com/images/dishes/50ea438b25cc416d8c0d977bc144fdbf.jpg?mw=1300", description: "Traditionally prepared and consumed by the Ngemba people from the Northwest Region of Cameroon, achu soup consists of boiled and pounded cocoyams, canwa (lime stone), water, spices, and palm oil. The palm oil changes the color of the soup to yellow, which is the reason why achu soup is also known as yellow soup.", price: 400, menu_id: 3},
    {name: "Afang Soup", image_url: "https://cdn.tasteatlas.com/images/dishes/662c50d9d8ec4760bb12d705f64897d6.jpg?mw=1300", description: "Afang is a traditional soup hailing from the southeastern parts of Nigeria. It's made with a combination of afang leaves, water leaves, dried fish, beef, onions, red palm oil, ground crayfish, and seasoning cubes. The afang leaves are ground or pounded and the onions are chopped before the beef is boiled with the onions and seasoning cubes in a small quantity of water.", price: 400, menu_id: 3},


    {name: "Loubia", image_url: "https://cdn.tasteatlas.com/Images/Dishes/81b54d44a09b43ce90e89ecf447d11f7.jpg?mw=1300", description: "This Morrocan dish consists of stewed white beans, where the beans that have been simmered in a zesty tomato-based sauce are typically scooped up with Moroccan bread. It is comfort food that can be served both as an appetizer, garnished with some coriander or parsley, and as a side dish - especially when used as an accompaniment to fried fish.", price: 750, menu_id: 4},
    {name: "Moin moin", image_url: "https://cdn.tasteatlas.com/images/dishes/87f9257608154f22bbdceea7d2f95fc9.jpg?mw=1300", description: "Moin moin is a Nigerian dish consisting of ground beans or black-eyed peas, onions, oil, and freshly ground peppers such as chili, bell pepper, and Scotch bonnet. The dish is usually served as an accompaniment to jollof rice, fried plantains, and akamu.", price: 750, menu_id: 4},
    {name: "Kafteji", image_url: "https://cdn.tasteatlas.com/images/dishes/31cd64e211564c3a8a8485f42e014773.jpg?mw=1300", description: "Kafteji is a traditional Tunisian dish made with fried vegetables. Typical veggies used in the dish include eggplants, bell peppers, potatoes, tomatoes, zucchinis, and pumpkins. The vegetables are fried, chopped, then combined with (often fried) eggs and seasonings.", price: 750, menu_id: 4},
    {name: "Mchicha", image_url: "https://cdn.tasteatlas.com/images/dishes/74bb396415974864b611c299280d3f1d.jpg?mw=1300", description: "Mchicha is the most popular Tanzanian dish. This thick and creamy vegetarian meal is usually prepared with leafy vegetables such as amaranth or spinach with added grated coconut, coconut milk, peanut butter, tomatoes, and onions. It is recommended to serve mchicha with rice, ugali, or samp and beans on the side in order to make a satisfying main course.", price: 750, menu_id: 4},
    {name: "Githeri", image_url: "https://cdn.tasteatlas.com/Images/Dishes/90200d42c5254588a0ec27df96271d15.jpg?mw=1300", description: "Githeri is a Kenyan staple food consisting of beans and maize that are stewed with onions, tomatoes, and sometimes potatoes or meat chunks. The stew is often flavored with cumin, turmeric, or chili powder. It is traditionally served on its own, although it can be served with rice or crusty bread on the side.", price: 750, menu_id: 4},
    {name: "Daraba", image_url: "https://cdn.tasteatlas.com/images/dishes/0661e7dea98644b3a9873ae9949bf9cd.jpg?mw=1300", description: "Simple, healthy, and inexpensive, daraba is a Chadian stew made with chopped okra, mixed vegetables, tomatoes, stock cubes, and smooth peanut butter, giving the dish a unique flavor. It is usually served with rice, boiled cassava, or boiled plantains on the side.", price: 750, menu_id: 4}

])



puts "✅ Done seeding"
